#!/bin/bash

#Move any existing tmp directory to new tmp directory
if test -e tmp; then
  echo "tmp already exists"
  rm -rf tmp
fi

#Read properties files.
. gradle.properties
. version.properties

#Create files, clone git repo
mkdir tmp
git clone https://github.com/chbachman/chbachman.github.io.git tmp

FILENAME="tmp/_posts/$(date +%Y-%m-%d)-Modular-Armour-Update!-Version-$mod_version.md"

touch $FILENAME

#Write the Header
echo "---
layout: post
categories: ModularArmour
---">> $FILENAME

#Start writing the post
CHANGELOG="Changelog here pls"
echo "A new Modular Armour version is available!

\`\`\`
$CHANGELOG
\`\`\`

Get the newest version at the [download site!](http://minecraft.curseforge.com/mc-mods/224011-modular-armour/files)
" >> $FILENAME

#Push to github, updating the website with the new post.
cd tmp
git add "_posts/$(date +%Y-%m-%d)-Modular-Armour-Update!-Version-$mod_version.md"
git commit -m "Update Modular Armour to Version $mod_version."
git push git@github.com:chbachman/chbachman.github.io.git
cd ..
