package chbachman.armour.items.armour.renderer;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class AdvancedArmourModel extends ModelBiped {

    // public ModelRenderer bipedHead;
    // public ModelRenderer bipedBody;
    // public ModelRenderer bipedRightArm;
    // public ModelRenderer bipedLeftArm;
    // public ModelRenderer bipedRightLeg;
    // public ModelRenderer bipedLeftLeg;

    public ModelRenderer MainHeadPieceRight1;
    public ModelRenderer MainHeadPieceRight2;
    public ModelRenderer MainHeadPieceRight3;
    public ModelRenderer DecorationGlass;
    public ModelRenderer HeadPieceBack1;
    public ModelRenderer HeadPieceTop1;
    public ModelRenderer MainHeadPieceFront4;
    public ModelRenderer MainHeadPieceFront3;
    public ModelRenderer MainHeadPieceFront1;
    public ModelRenderer MainHeadPieceFront2;
    public ModelRenderer HeadPieceLeft3;
    public ModelRenderer HeadPieceLeft2;
    public ModelRenderer HeadPieceLeft1;
    public ModelRenderer HeadPieceRight3;
    public ModelRenderer HeadPieceRight2;
    public ModelRenderer HeadPieceRight1;
    public ModelRenderer MainHeadPieceTop;
    public ModelRenderer MainHeadPieceBack;
    public ModelRenderer MainHeadPieceBottom;
    public ModelRenderer MainHeadPieceLeft3;
    public ModelRenderer MainHeadPieceLeft2;
    public ModelRenderer MainHeadPieceLeft1;
    public ModelRenderer TorsoMainPiece;
    public ModelRenderer TorsoPieceBig;
    public ModelRenderer TorsoPieceFront1;
    public ModelRenderer TorsoPieceFront2;
    public ModelRenderer TorsoPieceBack1;
    public ModelRenderer TorsoPieceBack2;
    public ModelRenderer TorsoPieceSideTopRight;
    public ModelRenderer TorsoPieceSideBottomRight;
    public ModelRenderer TorsoPieceSideTopLeft;
    public ModelRenderer TorsoPieceSideBottomLeft;
    public ModelRenderer ChestDecorationPiece8;
    public ModelRenderer ChestDecorationPiece7;
    public ModelRenderer ChestDecorationPiece6;
    public ModelRenderer ChestDecorationPiece5;
    public ModelRenderer ChestDecorationPiece4;
    public ModelRenderer ChestDecorationPiece3;
    public ModelRenderer ChestDecorationPiece2;
    public ModelRenderer ChestDecorationPiece1;
    public ModelRenderer ChestDecorationCenter;
    public ModelRenderer MainArmPieceRight;
    public ModelRenderer TopSholderPadRight;
    public ModelRenderer FrontShoulderPadRight;
    public ModelRenderer SideShoulderPadRight;
    public ModelRenderer BackShoulderPadRight;
    public ModelRenderer ArmDecorationRight1;
    public ModelRenderer TopSholderPadLeft;
    public ModelRenderer FrontShoulderPadLeft;
    public ModelRenderer MainArmPieceLeft;
    public ModelRenderer SideShoulderPadLeft;
    public ModelRenderer BackShoulderPadLeft;
    public ModelRenderer ArmDecorationLeft1;
    public ModelRenderer MainLegPieceRight;
    public ModelRenderer SideLegPieceRight1;
    public ModelRenderer SideBootPieceRight1;
    public ModelRenderer SideLegPieceRight2;
    public ModelRenderer SideBootPieceRight2;
    public ModelRenderer FrontBootPieceRight2;
    public ModelRenderer FrontBootPieceRight1;
    public ModelRenderer MainBootPieceRight;
    public ModelRenderer SideBootPieceRight3;
    public ModelRenderer SideBootPieceRight4;
    public ModelRenderer MainLegPieceLeft;
    public ModelRenderer MainBootPieceLeft;
    public ModelRenderer SideLegPieceLeft1;
    public ModelRenderer SideBootPieceLeft1;
    public ModelRenderer SideLegPieceLeft2;
    public ModelRenderer SideBootPieceLeft2;
    public ModelRenderer FrontBootPieceLeft1;
    public ModelRenderer FrontBootPieceLeft2;
    public ModelRenderer SideBootPieceLeft4;
    public ModelRenderer SideBootPieceLeft3;

    public AdvancedArmourModel(boolean renderHead, boolean renderBody, boolean renderArms, boolean renderLegs, boolean renderBoots) {
        this.textureWidth = 256;
        this.textureHeight = 128;

        this.ChestDecorationPiece6 = new ModelRenderer(this, 250, 66);
        this.ChestDecorationPiece6.setRotationPoint(-2.0F, 3.299999952316284F, -4.0F);
        this.ChestDecorationPiece6.addBox(0.0F, 3.4666666984558105F, 0.0F, 2, 1, 1, 0.0F);
        this.setRotateAngle(ChestDecorationPiece6, 0.0F, -0.0F, -0.7853981852531433F);
        this.MainLegPieceRight = new ModelRenderer(this, 206, 0);
        this.MainLegPieceRight.setRotationPoint(-2.0F, 0.0F, -2.5F);
        this.MainLegPieceRight.addBox(0.0F, 0.0F, 0.0F, 4, 8, 5, 0.0F);
        this.MainHeadPieceLeft3 = new ModelRenderer(this, 152, 0);
        this.MainHeadPieceLeft3.setRotationPoint(3.5F, -8.0F, -1.5F);
        this.MainHeadPieceLeft3.addBox(0.0F, 0.0F, 0.0F, 1, 8, 6, 0.0F);
        this.TorsoPieceSideBottomRight = new ModelRenderer(this, 242, 46);
        this.TorsoPieceSideBottomRight.setRotationPoint(-5.0F, 0.0F, -3.0F);
        this.TorsoPieceSideBottomRight.addBox(0.0F, 0.0F, 0.0F, 1, 5, 6, 0.0F);
        this.MainHeadPieceFront2 = new ModelRenderer(this, 134, 28);
        this.MainHeadPieceFront2.setRotationPoint(-4.5F, -2.0F, -5.0F);
        this.MainHeadPieceFront2.addBox(0.0F, 0.0F, 0.0F, 9, 1, 1, 0.0F);
        this.ArmDecorationRight1 = new ModelRenderer(this, 180, 33);
        this.ArmDecorationRight1.setRotationPoint(-4.0F, 3.0F, -1.0F);
        this.ArmDecorationRight1.addBox(0.0F, 0.0F, 0.0F, 1, 3, 2, 0.0F);
        this.MainHeadPieceRight3 = new ModelRenderer(this, 152, 0);
        this.MainHeadPieceRight3.setRotationPoint(-4.5F, -8.0F, -1.5F);
        this.MainHeadPieceRight3.addBox(0.0F, 0.0F, 0.0F, 1, 8, 6, 0.0F);
        this.BackShoulderPadRight = new ModelRenderer(this, 174, 19);
        this.BackShoulderPadRight.setRotationPoint(-3.5F, -2.0F, 2.0F);
        this.BackShoulderPadRight.addBox(0.0F, 0.0F, 0.0F, 5, 4, 1, 0.0F);
        this.MainHeadPieceFront1 = new ModelRenderer(this, 136, 30);
        this.MainHeadPieceFront1.setRotationPoint(-4.0F, -1.0F, -5.0F);
        this.MainHeadPieceFront1.addBox(0.0F, 0.0F, 0.0F, 8, 1, 1, 0.0F);
        this.FrontBootPieceRight2 = new ModelRenderer(this, 200, 18);
        this.FrontBootPieceRight2.setRotationPoint(-1.0F, 7.5F, -3.0F);
        this.FrontBootPieceRight2.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.HeadPieceBack1 = new ModelRenderer(this, 150, 44);
        this.HeadPieceBack1.setRotationPoint(-3.5F, -7.5F, 4.5F);
        this.HeadPieceBack1.addBox(0.0F, 0.0F, 0.0F, 7, 7, 1, 0.0F);
        this.SideBootPieceRight4 = new ModelRenderer(this, 202, 24);
        this.SideBootPieceRight4.setRotationPoint(1.5F, 9.0F, -3.0F);
        this.SideBootPieceRight4.addBox(0.0F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
        this.SideShoulderPadRight = new ModelRenderer(this, 174, 24);
        this.SideShoulderPadRight.setRotationPoint(-4.0F, -2.0F, -2.5F);
        this.SideShoulderPadRight.addBox(0.0F, 0.0F, 0.0F, 1, 4, 5, 0.0F);
        this.ChestDecorationCenter = new ModelRenderer(this, 248, 60);
        this.ChestDecorationCenter.setRotationPoint(0.0F, 2.0F, -4.0F);
        this.ChestDecorationCenter.addBox(0.0F, 0.0F, 0.0F, 3, 3, 1, 0.0F);
        this.setRotateAngle(ChestDecorationCenter, 0.0F, -0.0F, 0.7853981852531433F);
        this.ChestDecorationPiece8 = new ModelRenderer(this, 250, 66);
        this.ChestDecorationPiece8.setRotationPoint(-2.0F, 3.299999952316284F, -4.0F);
        this.ChestDecorationPiece8.addBox(1.0F, -3.5333333015441895F, 0.0F, 2, 1, 1, 0.0F);
        this.setRotateAngle(ChestDecorationPiece8, 0.0F, -0.0F, 0.7853981852531433F);
        this.SideShoulderPadLeft = new ModelRenderer(this, 174, 24);
        this.SideShoulderPadLeft.setRotationPoint(3.0F, -2.0F, -2.5F);
        this.SideShoulderPadLeft.addBox(0.0F, 0.0F, 0.0F, 1, 4, 5, 0.0F);
        this.SideLegPieceRight2 = new ModelRenderer(this, 214, 13);
        this.SideLegPieceRight2.setRotationPoint(1.5F, 0.0F, -2.0F);
        this.SideLegPieceRight2.addBox(0.0F, 0.0F, 0.0F, 1, 8, 4, 0.0F);
        this.MainHeadPieceFront4 = new ModelRenderer(this, 136, 30);
        this.MainHeadPieceFront4.setRotationPoint(-4.0F, -8.0F, -5.0F);
        this.MainHeadPieceFront4.addBox(0.0F, 0.0F, 0.0F, 8, 1, 1, 0.0F);
        this.FrontShoulderPadRight = new ModelRenderer(this, 174, 19);
        this.FrontShoulderPadRight.setRotationPoint(-3.5F, -2.0F, -3.0F);
        this.FrontShoulderPadRight.addBox(0.0F, 0.0F, 0.0F, 5, 4, 1, 0.0F);
        this.SideLegPieceLeft1 = new ModelRenderer(this, 214, 13);
        this.SideLegPieceLeft1.setRotationPoint(1.5F, 0.0F, -2.0F);
        this.SideLegPieceLeft1.addBox(0.0F, 0.0F, 0.0F, 1, 8, 4, 0.0F);
        this.TorsoMainPiece = new ModelRenderer(this, 226, 0);
        this.TorsoMainPiece.setRotationPoint(-4.5F, 0.0F, -3.0F);
        this.TorsoMainPiece.addBox(0.0F, 0.0F, 0.0F, 9, 12, 6, 0.0F);
        this.SideBootPieceRight2 = new ModelRenderer(this, 196, 10);
        this.SideBootPieceRight2.setRotationPoint(1.5F, 8.0F, -2.0F);
        this.SideBootPieceRight2.addBox(0.0F, 0.0F, 0.0F, 1, 4, 4, 0.0F);
        this.TorsoPieceBig = new ModelRenderer(this, 224, 18);
        this.TorsoPieceBig.setRotationPoint(-4.5F, 0.0F, -3.5F);
        this.TorsoPieceBig.addBox(0.0F, 0.0F, 0.0F, 9, 5, 7, 0.0F);
        this.HeadPieceTop1 = new ModelRenderer(this, 136, 35);
        this.HeadPieceTop1.setRotationPoint(-3.5F, -9.0F, -4.0F);
        this.HeadPieceTop1.addBox(0.0F, 0.0F, 0.0F, 7, 1, 8, 0.0F);
        this.TopSholderPadRight = new ModelRenderer(this, 170, 14);
        this.TopSholderPadRight.setRotationPoint(-3.0F, -3.0F, -2.0F);
        this.TopSholderPadRight.addBox(0.0F, 0.0F, 0.0F, 4, 1, 4, 0.0F);
        this.MainHeadPieceRight1 = new ModelRenderer(this, 144, 0);
        this.MainHeadPieceRight1.setRotationPoint(-4.5F, -8.0F, -4.5F);
        this.MainHeadPieceRight1.addBox(0.0F, 0.0F, 0.0F, 1, 2, 3, 0.0F);
        this.MainArmPieceRight = new ModelRenderer(this, 166, 0);
        this.MainArmPieceRight.setRotationPoint(-3.5F, -2.5F, -2.5F);
        this.MainArmPieceRight.addBox(0.0F, 0.0F, 0.0F, 5, 9, 5, 0.0F);
        this.BackShoulderPadLeft = new ModelRenderer(this, 174, 19);
        this.BackShoulderPadLeft.setRotationPoint(-1.5F, -2.0F, 2.0F);
        this.BackShoulderPadLeft.addBox(0.0F, 0.0F, 0.0F, 5, 4, 1, 0.0F);
        this.MainHeadPieceFront3 = new ModelRenderer(this, 134, 28);
        this.MainHeadPieceFront3.setRotationPoint(-4.5F, -7.0F, -5.0F);
        this.MainHeadPieceFront3.addBox(0.0F, 0.0F, 0.0F, 9, 1, 1, 0.0F);
        this.FrontBootPieceRight1 = new ModelRenderer(this, 198, 20);
        this.FrontBootPieceRight1.setRotationPoint(-1.5F, 9.0F, -4.0F);
        this.FrontBootPieceRight1.addBox(0.0F, 0.0F, 0.0F, 3, 3, 1, 0.0F);
        this.ChestDecorationPiece3 = new ModelRenderer(this, 250, 66);
        this.ChestDecorationPiece3.setRotationPoint(-2.0F, 3.299999952316284F, -4.5F);
        this.ChestDecorationPiece3.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.setRotateAngle(ChestDecorationPiece3, 0.0F, -0.0F, -0.7853981852531433F);
        this.HeadPieceRight3 = new ModelRenderer(this, 154, 24);
        this.HeadPieceRight3.setRotationPoint(-5.0F, -7.0F, -1.5F);
        this.HeadPieceRight3.addBox(0.0F, 0.0F, 0.0F, 1, 6, 5, 0.0F);
        this.TorsoPieceBack1 = new ModelRenderer(this, 240, 30);
        this.TorsoPieceBack1.setRotationPoint(-3.5F, 5.0F, 2.5F);
        this.TorsoPieceBack1.addBox(0.0F, 0.0F, 0.0F, 7, 1, 1, 0.0F);
        this.SideLegPieceLeft2 = new ModelRenderer(this, 214, 13);
        this.SideLegPieceLeft2.setRotationPoint(-2.5F, 0.0F, -2.0F);
        this.SideLegPieceLeft2.addBox(0.0F, 0.0F, 0.0F, 1, 8, 4, 0.0F);
        this.SideBootPieceLeft2 = new ModelRenderer(this, 196, 10);
        this.SideBootPieceLeft2.setRotationPoint(-2.5F, 8.0F, -2.0F);
        this.SideBootPieceLeft2.addBox(0.0F, 0.0F, 0.0F, 1, 4, 4, 0.0F);
        this.HeadPieceLeft3 = new ModelRenderer(this, 154, 24);
        this.HeadPieceLeft3.setRotationPoint(4.0F, -7.0F, -1.5F);
        this.HeadPieceLeft3.addBox(0.0F, 0.0F, 0.0F, 1, 6, 5, 0.0F);
        this.SideBootPieceRight1 = new ModelRenderer(this, 196, 10);
        this.SideBootPieceRight1.setRotationPoint(-2.5F, 8.0F, -2.0F);
        this.SideBootPieceRight1.addBox(0.0F, 0.0F, 0.0F, 1, 4, 4, 0.0F);
        this.TorsoPieceSideTopLeft = new ModelRenderer(this, 244, 34);
        this.TorsoPieceSideTopLeft.setRotationPoint(4.0F, 5.0F, -2.5F);
        this.TorsoPieceSideTopLeft.addBox(0.0F, 0.0F, 0.0F, 1, 7, 5, 0.0F);
        this.HeadPieceRight1 = new ModelRenderer(this, 146, 24);
        this.HeadPieceRight1.setRotationPoint(-5.0F, -2.0F, -4.5F);
        this.HeadPieceRight1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 3, 0.0F);
        this.TorsoPieceSideTopRight = new ModelRenderer(this, 244, 34);
        this.TorsoPieceSideTopRight.setRotationPoint(-5.0F, 5.0F, -2.5F);
        this.TorsoPieceSideTopRight.addBox(0.0F, 0.0F, 0.0F, 1, 7, 5, 0.0F);
        this.ChestDecorationPiece7 = new ModelRenderer(this, 250, 66);
        this.ChestDecorationPiece7.setRotationPoint(-2.0F, 3.299999952316284F, -4.0F);
        this.ChestDecorationPiece7.addBox(1.0F, 0.46666666865348816F, 0.0F, 2, 1, 1, 0.0F);
        this.setRotateAngle(ChestDecorationPiece7, 0.0F, -0.0F, 0.7853981852531433F);
        this.SideLegPieceRight1 = new ModelRenderer(this, 214, 13);
        this.SideLegPieceRight1.setRotationPoint(-2.5F, 0.0F, -2.0F);
        this.SideLegPieceRight1.addBox(0.0F, 0.0F, 0.0F, 1, 8, 4, 0.0F);
        this.SideBootPieceRight3 = new ModelRenderer(this, 202, 24);
        this.SideBootPieceRight3.setRotationPoint(-2.5F, 9.0F, -3.0F);
        this.SideBootPieceRight3.addBox(0.0F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
        this.TorsoPieceBack2 = new ModelRenderer(this, 246, 32);
        this.TorsoPieceBack2.setRotationPoint(-2.0F, 6.0F, 2.5F);
        this.TorsoPieceBack2.addBox(0.0F, 0.0F, 0.0F, 4, 1, 1, 0.0F);
        this.DecorationGlass = new ModelRenderer(this, 142, 52);
        this.DecorationGlass.setRotationPoint(-4.5F, -6.0F, -4.5F);
        this.DecorationGlass.addBox(0.0F, 0.0F, 0.0F, 9, 4, 3, 0.0F);
        this.TorsoPieceFront2 = new ModelRenderer(this, 246, 32);
        this.TorsoPieceFront2.setRotationPoint(-2.0F, 6.0F, -3.5F);
        this.TorsoPieceFront2.addBox(0.0F, 0.0F, 0.0F, 4, 1, 1, 0.0F);
        this.MainBootPieceRight = new ModelRenderer(this, 186, 0);
        this.MainBootPieceRight.setRotationPoint(-2.0F, 8.0F, -3.5F);
        this.MainBootPieceRight.addBox(0.0F, 0.0F, 0.0F, 4, 4, 6, 0.0F);
        this.HeadPieceRight2 = new ModelRenderer(this, 146, 24);
        this.HeadPieceRight2.setRotationPoint(-5.0F, -7.0F, -4.5F);
        this.HeadPieceRight2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 3, 0.0F);
        this.MainLegPieceLeft = new ModelRenderer(this, 206, 0);
        this.MainLegPieceLeft.setRotationPoint(-2.0F, 0.0F, -2.5F);
        this.MainLegPieceLeft.addBox(0.0F, 0.0F, 0.0F, 4, 8, 5, 0.0F);
        this.FrontBootPieceLeft2 = new ModelRenderer(this, 200, 18);
        this.FrontBootPieceLeft2.setRotationPoint(-1.0F, 7.5F, -3.0F);
        this.FrontBootPieceLeft2.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.HeadPieceLeft1 = new ModelRenderer(this, 146, 24);
        this.HeadPieceLeft1.setRotationPoint(4.0F, -2.0F, -4.5F);
        this.HeadPieceLeft1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 3, 0.0F);
        this.MainBootPieceLeft = new ModelRenderer(this, 186, 0);
        this.MainBootPieceLeft.setRotationPoint(-2.0F, 8.0F, -3.5F);
        this.MainBootPieceLeft.addBox(0.0F, 0.0F, 0.0F, 4, 4, 6, 0.0F);
        this.ChestDecorationPiece5 = new ModelRenderer(this, 250, 66);
        this.ChestDecorationPiece5.setRotationPoint(-2.0F, 3.299999952316284F, -4.0F);
        this.ChestDecorationPiece5.addBox(0.0F, -0.5333333611488342F, 0.0F, 2, 1, 1, 0.0F);
        this.setRotateAngle(ChestDecorationPiece5, 0.0F, -0.0F, -0.7853981852531433F);
        this.MainHeadPieceLeft2 = new ModelRenderer(this, 144, 0);
        this.MainHeadPieceLeft2.setRotationPoint(3.5F, -2.0F, -4.5F);
        this.MainHeadPieceLeft2.addBox(0.0F, 0.0F, 0.0F, 1, 2, 3, 0.0F);
        this.MainHeadPieceLeft1 = new ModelRenderer(this, 144, 0);
        this.MainHeadPieceLeft1.setRotationPoint(3.5F, -8.0F, -4.5F);
        this.MainHeadPieceLeft1.addBox(0.0F, 0.0F, 0.0F, 1, 2, 3, 0.0F);
        this.TopSholderPadLeft = new ModelRenderer(this, 170, 14);
        this.TopSholderPadLeft.setRotationPoint(-1.0F, -3.0F, -2.0F);
        this.TopSholderPadLeft.addBox(0.0F, 0.0F, 0.0F, 4, 1, 4, 0.0F);
        this.MainHeadPieceTop = new ModelRenderer(this, 132, 14);
        this.MainHeadPieceTop.setRotationPoint(-4.0F, -8.5F, -4.5F);
        this.MainHeadPieceTop.addBox(0.0F, 0.0F, 0.0F, 8, 1, 9, 0.0F);
        this.TorsoPieceFront1 = new ModelRenderer(this, 240, 30);
        this.TorsoPieceFront1.setRotationPoint(-3.5F, 5.0F, -3.5F);
        this.TorsoPieceFront1.addBox(0.0F, 0.0F, 0.0F, 7, 1, 1, 0.0F);
        this.SideBootPieceLeft1 = new ModelRenderer(this, 196, 10);
        this.SideBootPieceLeft1.setRotationPoint(1.5F, 8.0F, -2.0F);
        this.SideBootPieceLeft1.addBox(0.0F, 0.0F, 0.0F, 1, 4, 4, 0.0F);
        this.ChestDecorationPiece2 = new ModelRenderer(this, 246, 64);
        this.ChestDecorationPiece2.setRotationPoint(-2.0F, 3.299999952316284F, -4.5F);
        this.ChestDecorationPiece2.addBox(0.0F, 0.0F, 0.0F, 4, 1, 1, 0.0F);
        this.setRotateAngle(ChestDecorationPiece2, 0.0F, -0.0F, 0.7853981852531433F);
        this.SideBootPieceLeft3 = new ModelRenderer(this, 202, 24);
        this.SideBootPieceLeft3.setRotationPoint(1.5F, 9.0F, -3.0F);
        this.SideBootPieceLeft3.addBox(0.0F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
        this.ChestDecorationPiece4 = new ModelRenderer(this, 250, 66);
        this.ChestDecorationPiece4.setRotationPoint(-2.0F, 3.299999952316284F, -4.5F);
        this.ChestDecorationPiece4.addBox(0.0F, 3.0F, 0.0F, 2, 1, 1, 0.0F);
        this.setRotateAngle(ChestDecorationPiece4, 0.0F, -0.0F, -0.7853981852531433F);
        this.ArmDecorationLeft1 = new ModelRenderer(this, 180, 33);
        this.ArmDecorationLeft1.setRotationPoint(3.0F, 3.0F, -1.0F);
        this.ArmDecorationLeft1.addBox(0.0F, 0.0F, 0.0F, 1, 3, 2, 0.0F);
        this.HeadPieceLeft2 = new ModelRenderer(this, 146, 24);
        this.HeadPieceLeft2.setRotationPoint(4.0F, -7.0F, -4.5F);
        this.HeadPieceLeft2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 3, 0.0F);
        this.ChestDecorationPiece1 = new ModelRenderer(this, 246, 64);
        this.ChestDecorationPiece1.setRotationPoint(0.0F, 1.2999999523162842F, -4.5F);
        this.ChestDecorationPiece1.addBox(0.0F, 0.0F, 0.0F, 4, 1, 1, 0.0F);
        this.setRotateAngle(ChestDecorationPiece1, 0.0F, -0.0F, 0.7853981852531433F);
        this.MainHeadPieceBack = new ModelRenderer(this, 134, 5);
        this.MainHeadPieceBack.setRotationPoint(-4.0F, -8.0F, 4.0F);
        this.MainHeadPieceBack.addBox(0.0F, 0.0F, 0.0F, 8, 8, 1, 0.0F);
        this.MainHeadPieceBottom = new ModelRenderer(this, 132, 14);
        this.MainHeadPieceBottom.setRotationPoint(-4.0F, -0.5F, -4.5F);
        this.MainHeadPieceBottom.addBox(0.0F, 0.0F, 0.0F, 8, 1, 9, 0.0F);
        this.FrontBootPieceLeft1 = new ModelRenderer(this, 198, 20);
        this.FrontBootPieceLeft1.setRotationPoint(-1.5F, 9.03F, -4.0F);
        this.FrontBootPieceLeft1.addBox(0.0F, 0.0F, 0.0F, 3, 3, 1, 0.0F);
        this.TorsoPieceSideBottomLeft = new ModelRenderer(this, 242, 46);
        this.TorsoPieceSideBottomLeft.setRotationPoint(4.0F, 0.0F, -3.0F);
        this.TorsoPieceSideBottomLeft.addBox(0.0F, 0.0F, 0.0F, 1, 5, 6, 0.0F);
        this.SideBootPieceLeft4 = new ModelRenderer(this, 202, 24);
        this.SideBootPieceLeft4.setRotationPoint(-2.5F, 9.0F, -3.0F);
        this.SideBootPieceLeft4.addBox(0.0F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
        this.MainArmPieceLeft = new ModelRenderer(this, 166, 0);
        this.MainArmPieceLeft.setRotationPoint(-1.5F, -2.5F, -2.5F);
        this.MainArmPieceLeft.addBox(0.0F, 0.0F, 0.0F, 5, 9, 5, 0.0F);
        this.MainHeadPieceRight2 = new ModelRenderer(this, 144, 0);
        this.MainHeadPieceRight2.setRotationPoint(-4.5F, -2.0F, -4.5F);
        this.MainHeadPieceRight2.addBox(0.0F, 0.0F, 0.0F, 1, 2, 3, 0.0F);
        this.FrontShoulderPadLeft = new ModelRenderer(this, 174, 19);
        this.FrontShoulderPadLeft.setRotationPoint(-1.5F, -2.0F, -3.0F);
        this.FrontShoulderPadLeft.addBox(0.0F, 0.0F, 0.0F, 5, 4, 1, 0.0F);

        this.bipedBody.cubeList.clear();
        this.bipedHead.cubeList.clear();
        this.bipedLeftArm.cubeList.clear();
        this.bipedRightArm.cubeList.clear();
        this.bipedLeftLeg.cubeList.clear();
        this.bipedRightLeg.cubeList.clear();

        if (renderHead) {
            this.bipedHead.addChild(this.MainHeadPieceLeft3);
            this.bipedHead.addChild(this.MainHeadPieceFront2);
            this.bipedHead.addChild(this.MainHeadPieceRight3);
            this.bipedHead.addChild(this.MainHeadPieceFront1);
            this.bipedHead.addChild(this.HeadPieceBack1);
            this.bipedHead.addChild(this.MainHeadPieceFront4);
            this.bipedHead.addChild(this.HeadPieceTop1);
            this.bipedHead.addChild(this.MainHeadPieceRight1);
            this.bipedHead.addChild(this.MainHeadPieceFront3);
            this.bipedHead.addChild(this.HeadPieceLeft3);
            this.bipedHead.addChild(this.HeadPieceRight1);
            this.bipedHead.addChild(this.DecorationGlass);
            this.bipedHead.addChild(this.MainHeadPieceLeft1);
            this.bipedHead.addChild(this.MainHeadPieceTop);
            this.bipedHead.addChild(this.HeadPieceRight3);
            this.bipedHead.addChild(this.HeadPieceRight2);
            this.bipedHead.addChild(this.HeadPieceLeft1);
            this.bipedHead.addChild(this.MainHeadPieceLeft2);
            this.bipedHead.addChild(this.HeadPieceLeft2);
            this.bipedHead.addChild(this.MainHeadPieceBack);
            this.bipedHead.addChild(this.MainHeadPieceRight2);
            this.bipedHead.addChild(this.MainHeadPieceBottom);

        }

        if (renderBody) {
            this.bipedBody.addChild(this.ChestDecorationPiece6);
            this.bipedBody.addChild(this.TorsoPieceSideBottomRight);
            this.bipedBody.addChild(this.ChestDecorationCenter);
            this.bipedBody.addChild(this.ChestDecorationPiece8);
            this.bipedBody.addChild(this.TorsoMainPiece);
            this.bipedBody.addChild(this.TorsoPieceBig);
            this.bipedBody.addChild(this.ChestDecorationPiece3);
            this.bipedBody.addChild(this.TorsoPieceBack1);
            this.bipedBody.addChild(this.TorsoPieceSideTopLeft);
            this.bipedBody.addChild(this.TorsoPieceSideTopRight);
            this.bipedBody.addChild(this.ChestDecorationPiece7);
            this.bipedBody.addChild(this.TorsoPieceBack2);
            this.bipedBody.addChild(this.TorsoPieceFront2);
            this.bipedBody.addChild(this.ChestDecorationPiece5);
            this.bipedBody.addChild(this.TorsoPieceFront1);
            this.bipedBody.addChild(this.ChestDecorationPiece2);
            this.bipedBody.addChild(this.ChestDecorationPiece4);
            this.bipedBody.addChild(this.ChestDecorationPiece1);
            this.bipedBody.addChild(this.TorsoPieceSideBottomLeft);
        }

        if (renderArms) {
            this.bipedRightArm.addChild(this.ArmDecorationRight1);
            this.bipedRightArm.addChild(this.BackShoulderPadRight);
            this.bipedRightArm.addChild(this.SideShoulderPadRight);
            this.bipedLeftArm.addChild(this.SideShoulderPadLeft);
            this.bipedRightArm.addChild(this.FrontShoulderPadRight);
            this.bipedRightArm.addChild(this.TopSholderPadRight);
            this.bipedRightArm.addChild(this.MainArmPieceRight);
            this.bipedLeftArm.addChild(this.BackShoulderPadLeft);
            this.bipedLeftArm.addChild(this.TopSholderPadLeft);
            this.bipedLeftArm.addChild(this.ArmDecorationLeft1);
            this.bipedLeftArm.addChild(this.MainArmPieceLeft);
            this.bipedLeftArm.addChild(this.FrontShoulderPadLeft);

        }

        if (renderLegs) {
            this.bipedRightLeg.addChild(this.MainLegPieceRight);
            this.bipedRightLeg.addChild(this.SideLegPieceRight2);
            this.bipedLeftLeg.addChild(this.SideLegPieceLeft1);
            this.bipedLeftLeg.addChild(this.SideLegPieceLeft2);
            this.bipedRightLeg.addChild(this.SideLegPieceRight1);
            this.bipedLeftLeg.addChild(this.MainLegPieceLeft);
        }

        if (renderBoots) {
            this.bipedRightLeg.addChild(this.FrontBootPieceRight2);
            this.bipedRightLeg.addChild(this.SideBootPieceRight4);
            this.bipedRightLeg.addChild(this.SideBootPieceRight2);
            this.bipedRightLeg.addChild(this.FrontBootPieceRight1);
            this.bipedLeftLeg.addChild(this.SideBootPieceLeft2);
            this.bipedRightLeg.addChild(this.SideBootPieceRight1);
            this.bipedRightLeg.addChild(this.SideBootPieceRight3);
            this.bipedRightLeg.addChild(this.MainBootPieceRight);
            this.bipedLeftLeg.addChild(this.FrontBootPieceLeft2);
            this.bipedLeftLeg.addChild(this.MainBootPieceLeft);
            this.bipedLeftLeg.addChild(this.SideBootPieceLeft1);
            this.bipedLeftLeg.addChild(this.SideBootPieceLeft3);
            this.bipedLeftLeg.addChild(this.FrontBootPieceLeft1);
            this.bipedLeftLeg.addChild(this.SideBootPieceLeft4);
        }

    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.bipedRightArm.render(f5);
        this.bipedHead.render(f5);
        this.bipedBody.render(f5);
        this.bipedLeftArm.render(f5);
        this.bipedRightLeg.render(f5);
        this.bipedLeftLeg.render(f5);
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
